language: java
matrix:
  include:
    - jdk: oraclejdk8
    # https://www.deps.co/guides/travis-ci-latest-java/#certificate-issues
    - jdk: openjdk9
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - jdk: openjdk10
      before_install:
       - rm "${JAVA_HOME}/lib/security/cacerts"
       - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - jdk: openjdk11
      before_install:
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

# notice:check is disabled because build with JDK > 8 ignores excludes         
#script: mvn -fae -U -B clean license:check notice:check install -P check
script: mvn -fae -U -B clean license:check install -P check
after_success: 
- chmod +x .travis/deploy-docs.sh && .travis/deploy-docs.sh
- curl -Ls https://git.io/deploy-maven-snapshot | bash
# start dependend builds
- curl -Ls https://git.io/trigger-build | bash -s -- 52North/dao-series-api "version/v3.x" 
env:
  global:
    - SNAPSHOT_BRANCH=v2.x/feature/jpa-xml
cache:
  directories
    - $HOME/.m2
notifications:
  irc:
    channels:
      - "chat.freenode.net#52north"
    on_failure: always
