
spring:
  datasource:
    username: 
    password: 
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    initialization-mode: always
  jpa:
    properties:
      hibernate: 
        hbm2ddl:
          # hbm2ddl values: validate | update | create | create-drop
          auto: create
        jdbc:
          zone: UTC
        default_schema: public
        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
        format_sql: true

logging:
  config: classpath:logback.xml
  level:
    root: INFO
#    com.querydsl: DEBUG
    org:
      n52: INFO
#      hibernate: INFO
      hibernate.SQL: DEBUG
#      hibernate.type: TRACE
#      springframework: INFO
